name: photojam_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.4+2


environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.4.0
  cupertino_icons: ^1.0.8
  appwrite: ^13.0.0
  archive: ^3.3.1
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  image_picker: ^1.1.2
  flutter_markdown: ^0.7.4+1
  http: ^1.2.2
  intl: ^0.19.0
  path_provider: ^2.0.11 
  path: ^1.8.3
  url_launcher: ^6.1.7 
  file_picker: ^8.0.7
  crypto: ^3.0.6
  share_plus: ^10.1.1
  table_calendar: ^3.1.2
  reorderables: ^0.6.0
  add_2_calendar: ^3.0.1
  app_links: ^6.3.3
  get_it: ^8.0.2
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  # flutter_stripe: ^11.2.0
  # TODO square_in_app_payments: ^1.7.9


dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.4.5  # For code generation
  build_runner: ^2.4.6
  json_serializable: ^6.7.1  # If you need JSON serialization

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  assets:
    - assets/icon/app_icon.png
    - assets/icon/app_icon_transparent.png
    - assets/images/qrcode.png
    - assets/google_icon.svg
    - assets/apple_icon.svg
    - assets/github_icon.svg
    - assets/twitter_icon.svg

  uses-material-design: true